#!/usr/bin/env python3
"""Generate test/test_astro/golden.h: reference values for the C++ port in lib/core.

The RA/HA functions below are copied from lx200.py, with the sidereal time passed
in instead of read from ephem, so the C++ port is checked against the exact Python
arithmetic. Sidereal time itself comes from ephem, used correctly (UTC, longitude
in degrees). Run: python3 test/gen_golden.py
"""
import math
import os
import random
from datetime import datetime, timezone

import ephem

LON = 14.4377
OFFSET = 2  # offset_star_adventurer


# --- copied from lx200.py (ephem call replaced by the lst argument) ---
def get_hour_angle(ra, lst):
    return (lst - ra) % 360.0 + OFFSET


def get_right_ascension(ha, lst):
    ha = ha - OFFSET
    return (lst - ha) % 360.0


def set_ra_target(ra_target_temp, lst):
    if get_hour_angle(ra_target_temp, lst) > 180:
        return get_right_ascension(get_hour_angle(ra_target_temp + 180, lst) % 360, lst), True
    return ra_target_temp, False


def get_ra(pos, flipped, lst):
    if flipped:
        pos = get_right_ascension((get_hour_angle(pos, lst) - 180) % 360, lst)
    return pos


step_per_rev_dec = 585600 / 2


def dec_to_steps(degrees):
    dec_in_centi_degrees = degrees * 3600.0
    return int(((dec_in_centi_degrees + 3600.0 * 180.0) / (3600.0 * 360.0)) * step_per_rev_dec)


def steps_to_normalized_dec(steps, reverse_dec):  # steps_to_coord() before formatting
    normalized_dec = (steps / step_per_rev_dec) * 360.0 - 180.0
    if reverse_dec:
        normalized_dec = ((180 - normalized_dec) + 180) % 360 - 180
    return normalized_dec


def set_dec_steps(degrees, reverse_dec):  # set_dec()
    if reverse_dec:
        degrees = 180 - degrees
    return dec_to_steps(degrees)


def time_to_degrees(hours, minutes, seconds):
    total_seconds = hours * 3600 + minutes * 60 + seconds
    normalized_seconds = total_seconds % (24 * 3600)
    return (normalized_seconds / (24 * 3600)) * 360.0


def degrees_to_hms(degrees):
    degrees = degrees % 360
    if degrees < 0:
        degrees += 360
    total_hours = degrees / 15
    hours = int(total_hours)
    remaining_minutes = (total_hours - hours) * 60
    minutes = int(remaining_minutes)
    seconds = int((remaining_minutes - minutes) * 60)
    return hours, minutes, seconds
# ---


def lst_ephem(unix):
    o = ephem.Observer()
    o.lon, o.lat = str(LON), '40.8728'
    o.date = datetime.fromtimestamp(unix, timezone.utc).replace(tzinfo=None)
    return math.degrees(o.sidereal_time())


random.seed(42)
out = ['// Generated by test/gen_golden.py - do not edit', '#pragma once', '']

times = [946728000, 1700000000, 1735689600, 1758570000, 1790000000, 1893456000]
times += [random.randint(1600000000, 2000000000) for _ in range(10)]
out.append('struct LstCase { double t; double lst; };')
out.append('static const LstCase LST_CASES[] = {')
out += [f'  {{{t}, {lst_ephem(t)!r}}},' for t in times]
out += ['};', '']

out.append('struct HaCase { double ra, lst, ha, raBack; };')
out.append('static const HaCase HA_CASES[] = {')
for _ in range(40):
    ra, lst = random.uniform(-10, 370), random.uniform(0, 360)
    ha = get_hour_angle(ra, lst)
    out.append(f'  {{{ra!r}, {lst!r}, {ha!r}, {get_right_ascension(ha, lst)!r}}},')
out += ['};', '']

out.append('struct TargetCase { double req, lst, ra; int flipped; double reported; };')
out.append('static const TargetCase TARGET_CASES[] = {')
for _ in range(60):
    req, lst = random.uniform(0, 360), random.uniform(0, 360)
    ra, flipped = set_ra_target(req, lst)
    out.append(f'  {{{req!r}, {lst!r}, {ra!r}, {int(flipped)}, {get_ra(ra, flipped, lst)!r}}},')
out += ['};', '']

out.append('struct HmsCase { double deg; int h, m, s; };')
out.append('static const HmsCase HMS_CASES[] = {')
for deg in [0, 0.004, 14.99999, 15, 187.3456, 359.9999, 360, -15.5, 721.25] + [random.uniform(0, 360) for _ in range(20)]:
    out.append(f'  {{{float(deg)!r}, {", ".join(map(str, degrees_to_hms(deg)))}}},')
out += ['};', '']

out.append('struct TimeDegCase { int h, m, s; double deg; };')
out.append('static const TimeDegCase TIMEDEG_CASES[] = {')
for h, m, s in [(0, 0, 0), (12, 30, 15), (23, 59, 59), (24, 0, 0), (25, 61, 61), (5, 35, 17)]:
    out.append(f'  {{{h}, {m}, {s}, {time_to_degrees(h, m, s)!r}}},')
out += ['};', '']

out.append('struct DecCase { double deg; int reverse; long steps; double back; };')
out.append('static const DecCase DEC_CASES[] = {')
for deg in [90, 0, -90, 45.5, -12.3456, 89.99, -89.99, 60.25] + [random.uniform(-90, 90) for _ in range(20)]:
    for rev in (0, 1):
        steps = set_dec_steps(deg, rev)
        out.append(f'  {{{float(deg)!r}, {rev}, {steps}, {steps_to_normalized_dec(steps, rev)!r}}},')
out += ['};', '']

path = os.path.join(os.path.dirname(__file__), 'test_astro', 'golden.h')
open(path, 'w').write('\n'.join(out))
print(f'wrote {path}')
